fix: send node down message only when nodes are "DOWN" or "DEGRADED"
aviate-labs/node-monitor pull request #105
Opened 2023-10-31 09:14 UTC by louisevelayo

### Description
Fixes #102 

### Changes made
- Add conditional statements in `get_compromised_nodes.py` to send a node down message if a node is down or degraded
- Refactor function and variable names from 'nodes_down' to 'nodes_compromised'

### Testing
All tests pass on existing testing suite

### Additional comments
N/A

2023-10-31 21:52 UTC, mourginakis requested changes

2023-10-31 21:52 UTC, mourginakis commented on node_monitor/node_monitor_helpers/get_compromised_nodes.py
> +            node_c.status == 'DOWN' or node_c.status == 'DEGRAGED',
![image](https://github.com/aviate-labs/node-monitor/assets/2019116/cb2c319e-8bd1-43f2-8392-f0cfc67663e8)
# 🤔🤔🤔

2023-11-02 12:54 UTC, louisevelayo commented on node_monitor/node_monitor_helpers/get_compromised_nodes.py
> +            node_c.status == 'DOWN' or node_c.status == 'DEGRAGED',
😶‍🌫️😶‍🌫️😶‍🌫️

2023-11-03 20:37 UTC, mourginakis approved these changes

2023-11-03 20:37 UTC, merged